// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-etybuwoDngOpz4djjwbIaCYetYk4vw',
    appId: '1:691081708098:web:e7f847538a3e46c7aea3db',
    messagingSenderId: '691081708098',
    projectId: 'tstoreapp-58777',
    authDomain: 'tstoreapp-58777.firebaseapp.com',
    storageBucket: 'tstoreapp-58777.appspot.com',
    measurementId: 'G-NWC5HVKW53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD60aTG8BZqQOYv0XdTdm3lv8XFQ6XlfjI',
    appId: '1:691081708098:android:bc40ec1d7df2beb5aea3db',
    messagingSenderId: '691081708098',
    projectId: 'tstoreapp-58777',
    storageBucket: 'tstoreapp-58777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVYmf5hZKWGDHcVTmF4RMPlEt_JJNYdgg',
    appId: '1:691081708098:ios:04f7f6f06f6f0f60aea3db',
    messagingSenderId: '691081708098',
    projectId: 'tstoreapp-58777',
    storageBucket: 'tstoreapp-58777.appspot.com',
    iosClientId: '691081708098-sjrrd9unk282i50lvhiudr20qfmh6j9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVYmf5hZKWGDHcVTmF4RMPlEt_JJNYdgg',
    appId: '1:691081708098:ios:6ce70259e70e365aaea3db',
    messagingSenderId: '691081708098',
    projectId: 'tstoreapp-58777',
    storageBucket: 'tstoreapp-58777.appspot.com',
    iosClientId: '691081708098-lmlng7u59a3aofj9s20atvgm23egrlsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore.RunnerTests',
  );
}
